Repository PdxCodeGuild/class_orchid, pull requests merged in 2022-07, with the labels that each got.

#22 01lab.py has been completed. Thank you.
  code/cesar/python/lab01.py
Labels: complete

#29 rob/python/lab02
  code/rob/python/lab02.py
Labels: complete

#24 rob/python/lab01
  code/rob/python/lab01.py
Labels: complete

#23 lab01 commit
  code/patrick/lab01.py
Labels: complete

#32 Both version 1 and 2 are in the same .py file
  code/cesar/python/lab02.py
Labels: complete

#25 Lab 01 complete. Thank you
  code/teyon/python/labs/lab01.py
Labels: complete

#31 Completed Lab 2 Version 2
  code/Jen/Python/average_numbers.py
  code/Jen/Python/average_numbers2.py
Labels: complete

#15 Jordyn/python/lab01
  code/jordyn/python/lab01.py
Labels: complete

#19 01lab conversion
  code/vel/python/01lab.py
Labels: complete

#20 Lab 2
  code/vel/python/02lab.py
Labels: complete

#21 Added Lab1
  code/Jen/Python/unit_converter.py
Labels: complete

#17 Lab02 with accidental Lab01 with it
  code/jordyn/python/lab02.py
Labels: complete

#26 lab01 complete
  code/mileidy/python/lab01_ver1.py
  code/mileidy/python/lab01_ver2.py
  code/mileidy/python/lab01_ver3.py
  code/mileidy/python/lab01_version4.py
Labels: complete

#28 lab02 completed
  code/mileidy/python/lab02_version1.py
  code/mileidy/python/lab02_version2.py
Labels: complete

#33 lab 03
  code/vel/python/03lab_ver1.py
  code/vel/python/03lab_ver2.py
Labels: complete

#37 rob/python/lab03
  code/rob/python/lab03.py
Labels: complete

#89 fake pr for example
  code/pete/python/fake_pr.py
Labels: complete

#43 lab04 complete
  code/jordyn/python/lab04.py
Labels: complete

#50 Lab 02 version 1 complete. Thank you
  code/teyon/lab02.py
  code/teyon/lab02v2.py
Labels: complete

#27 lab 1
  code/christa/python/01lab.py
Labels: complete

#47 Mileidy/python/lab03
  code/mileidy/python/lab03_version1.py
Labels: complete

#48 Tony/python/lab03
  code/tony/python/lab03version1.py
  code/tony/python/lab03version2.py
Labels: complete

#54 Patrick/python/lab02
  code/patrick/python/lab02ver1.py
  code/patrick/python/lab02ver2.py
Labels: complete

#60 Tony/python/lab01
  code/tony/python/lab01version1.py
  code/tony/python/lab01version2.py
  code/tony/python/lab01version3.py
  code/tony/python/lab01version4.py
Labels: complete

#77 04lab versions 1 and 2
  code/vel/04lab_ver1.py
  code/vel/04lab_ver2.py
Labels: complete

#58 submit lab 4.1 and 4.2
  code/christa/python/04labv1.py
  code/christa/python/04labv2.py
  code/christa/python/04labv3.py
Labels: complete

#75 lab03.py is complete. make change lab.
  code/cesar/lab03.py
Labels: complete

#74 added lab 4 v1 & v2
  code/Jen/lab4v1.py
  code/Jen/lab4v2.py
Labels: complete

#82 Luis/python/lab02
  code/luis/python/lab_02/lab_02.py
Labels: complete

#45 05lab
  code/vel/python/05lab.py
Labels: complete

#65 lab04 versions 1,2,3
  code/rob/python/lab04/lab04_v1.py
  code/rob/python/lab04/lab04_v2.py
  code/rob/python/lab04/lab04_v3.py
Labels: complete

#44 lab05 completed
  code/mileidy/python/lab05_version1.py
Labels: complete

#76 Lab05 is complete with both versions.
  code/cesar/lab05.py
Labels: complete

#93 Luis/python/lab04
  1 Python/labs/03 Make Change.md
  1 Python/labs/04 Number To Phrase.md
  1 Python/practice/06_dictionaries.py
  code/luis/python/Lab_04/lab_04_New.py
Labels: complete

#39 lab 02
  code/christa/python/02lab.py
Labels: complete

#42 Tony/python/lab02
  code/tony/python/lab02_version1.py
  code/tony/python/lab02_version2.py
Labels: complete

#78 [Lab05]Relearned Functions yay, includes optional
  code/jordyn/python/lab05.py
Labels: complete

#80 rob/python/lab05
  code/rob/python/lab05.py
Labels: complete

#94 I previously completed lab 1, I tried it with a dictionary.
  code/Jen/Python/converter_new.py
Labels: complete

#79 Lab 5 Version 1 added.
  code/Jen/lab5v1.py
Labels: complete

#100 Mileidy/python/lab04
  code/mileidy/python/lab04_version1.py
  code/mileidy/python/lab04_version2.py
Labels: complete

#95 submit v1 of lab 06 still working v2
  code/christa/python/06labv1.py
  code/christa/python/06labv2.py
Labels: complete

#98 lab06 v1
  code/rob/python/lab06/lab06.py
Labels: complete

#101 Lab06 versions 1 and 2 completed
  code/vel/python/lab06_ver1.py
  code/vel/python/lab06_ver2.py
Labels: complete

#99 lab06
  code/jordyn/python/lab06.py
Labels: complete

#34 patrick lab03 push
  code/patrick/python/lab03.py
Labels: incomplete

#55 Patrick/python/lab05
  code/patrick/python/lab05.py
Labels: complete

#91 Lab 6 v1 and v2 added
  code/Jen/Python/pick6.py
  code/Jen/Python/pick6v2.py
Labels: complete

#118 Mileidy/python/lab06
  code/mileidy/python/lab06_version1.py
  code/mileidy/python/lab06_version2.py
Labels: complete

#119 Lab06 is complete. Both versions are in this file/branch
  code/cesar/lab06.py
Labels: complete

#49 lab04 commit with lab2.1 and lab05
  code/patrick/python/lab04.1.py
  code/patrick/python/lab04.py
Labels: complete

#122 Tony/python/lab06
  code/tony/python/lab06version1.py
  code/tony/python/lab06version2.py
Labels: complete

#85 Lab 04/Versions 1 and 2, Thank you
  code/teyon/lab04v1.py
  code/teyon/lab04v2.py
Labels: complete

#81 This is Lab04.py Versions 1 and 2
  code/cesar/lab04v1.py
  code/cesar/lab04v2.py
  code/cesar/python/lab10.py
Labels: complete

#123 lab 08 complete, Thank you
  code/teyon/python/lab08.py
Labels: complete

#114 Lab 8 Credit Card Validation Completed.
  code/cesar/python/lab08.py
Labels: complete

#108 rob/python/lab08
  code/rob/python/lab08.py
Labels: complete

#105 Tony/python/lab08
  code/tony/python/lab08version1.py
Labels: complete

#104 lab08 completed
  code/jordyn/python/lab08.py
Labels: complete

#57 Tony/python/lab05
  code/tony/python/lab05version1.py
  code/tony/python/lab05version2.py
Labels: complete

#62 commit lab 05
  code/christa/python/05lab.py
Labels: complete

#102 Added lab 8
  code/Jen/Python/credit_card.py
Labels: complete

#109 Vel/python/lab08
  code/vel/python/lab06.py
  code/vel/python/lab08.py
Labels: complete

#110 added lab09
  code/Jen/Python/09peaksvalleys.py
Labels: complete

#112 Tony/python/lab09
  code/tony/python/lab09version1.py
  code/tony/python/lab09version2.py
  code/tony/python/lab09version3.py
Labels: complete

#115 rob/python/lab09
  code/rob/python/lab09/lab09_v1.py
Labels: complete

#125 lab 9 submission please grade
  code/christa/python/09lab.py
Labels: complete

#116 Vel/python/lab09
  code/vel/python/lab06.py
  code/vel/python/lab09_ver1.py
Labels: complete

#133 Lab 09 complete. Thank you
  code/teyon/lab09.py
Labels: complete

#111 lab 8 still working not complete
  code/christa/python/08lab.py
Labels: complete

#134 Lab09 is now complete. Thank you.
  code/cesar/python/lab09.py
Labels: complete

#140 Patrick/python/lab06
  code/patrick/python/lab06.py
  code/patrick/python/lab06ver2.py
Labels: complete

#61 Teyon/python/lab03
  code/teyon/lab03.py
Labels: complete

#150 Lab 10 ROT 13 is ready to be graded. Thanks!
  code/cesar/python/lab10.py
Labels: complete

#130 lab10v1
  code/faith/python/lab10v1.py
  code/faith/python/lab10v2.py
Labels: complete

#152 Christa/python/lab10
  code/christa/python/10lab.py
Labels: complete

#149 Lab09
  code/jordyn/python/lab09.py
Labels: complete

#153 Christa/python/lab11
  code/christa/python/11lab.py
  code/christa/python/war_and_peace.txt
Labels: complete

#126 convenient, if not sloppy use of list comprehension! 🍺
  code/tony/python/lab_road_trip_version_1.py
Labels: complete

#157 completed lab09
  code/mileidy/python/lab09_version1.py
Labels: complete

#144 lab 10 complete, Thank you
  code/teyon/python/labs/lab10.py
Labels: complete

#131 Added lab 10
  code/Jen/Python/10_rotcipher.py
Labels: complete

#135 lab10.py final
  code/patrick/python/lab10.py
Labels: complete

#137 completed la10
  code/mileidy/python/lab10_ver1_ls.py
  code/mileidy/python/lab10_version1.py
Labels: complete

#156 lab09 ready to grade
  code/patrick/python/lab09.py
Labels: complete

#132 Tony/python/lab10
  code/tony/python/lab10version1.py
  code/tony/python/lab10version2.py
Labels: complete

#129 rob/pyhton/lab10
  code/rob/python/lab10.py
Labels: complete

#158 Lab11 is ready to be graded.
  code/cesar/python/lab11.py
  code/cesar/python/thinketh.txt
Labels: complete

#148 Patrick/python/lab08
  code/patrick/python/lab08.py
Labels: complete

#151 rob/python/lab11
  code/rob/python/lab11/lab11.py
  code/rob/python/lab11/lab11.txt
Labels: complete

#147 lab11(works but might adjust)
  code/faith/python/lab11/book.txt
  code/faith/python/lab11/lab11.py
Labels: complete

#154 Tony/python/lab11
  code/tony/python/data/lab11books/A Dolls House  a play.txt
  code/tony/python/data/lab11books/A Modest Proposal For preventing the children of poor people.txt
  code/tony/python/data/lab11books/A Tale of Two Cities.txt
  code/tony/python/data/lab11books/Adventures of Huckleberry Finn.txt
  code/tony/python/data/lab11books/Alices Adventures in Wonderland.txt
  code/tony/python/data/lab11books/Birds from North Borneo University of Kansas Publications Museum of.txt
  code/tony/python/data/lab11books/Crime and Punishment.txt
  code/tony/python/data/lab11books/Dracula.txt
  code/tony/python/data/lab11books/Frankenstein Or The Modern Prometheus.txt
  code/tony/python/data/lab11books/Gettysburg Address.txt
  code/tony/python/data/lab11books/Great Expectations.txt
  code/tony/python/data/lab11books/Heart of Darkness.txt
  code/tony/python/data/lab11books/Jane Eyre An Autobiography.txt
  code/tony/python/data/lab11books/Japanese Girls and Women Revised and Enlarged Edition.txt
  code/tony/python/data/lab11books/Metamorphosis.txt
  code/tony/python/data/lab11books/Moby Dick Or The Whale.txt
  code/tony/python/data/lab11books/Noli Me Tangere.txt
  code/tony/python/data/lab11books/The Count of Monte Cristo Illustrated.txt
  code/tony/python/data/lab11books/The Great Gatsby.txt
  code/tony/python/data/lab11books/The Iliad.txt
  code/tony/python/data/lab11books/The Importance of Being Earnest A Trivial Comedy for Serious.txt
  code/tony/python/data/lab11books/The Picture of Dorian Gray.txt
  code/tony/python/data/lab11books/The Prince.txt
  code/tony/python/data/lab11books/The Romance of Lust A classic Victorian erotic novel.txt
  code/tony/python/data/lab11books/The Yellow Wallpaper.txt
  code/tony/python/data/lab11books/Treasure Island.txt
  code/tony/python/data/lab11books/War and Peace.txt
  code/tony/python/lab11.py
Labels: complete

#145 lab11 ready for grading
  code/patrick/python/data/sence.txt
  code/patrick/python/lab11.py
Labels: complete

#139 Lab 11
  code/Jen/Python/11_ari.py
  code/Jen/Python/underground.txt
Labels: complete

#146 Vel/python/lab11
  code/vel/python/lab11.py
  code/vel/python/the_raven/the_raven.txt
Labels: complete

#138 Mileidy/python/lab08
  code/mileidy/python/lab08_version1.py
  code/mileidy/python/test.py
Labels: complete

#121 Teyon/python/lab06
  code/teyon/python/lab06.py
  code/teyon/python/lab06v2.py
Labels: help wanted, complete

#136 Vel/python/lab10
  code/vel/python/lab10.py
Labels: help wanted, complete

#127 fixed a link
  1 Python/docs/08 Strings.md
Labels: documentation

#155 Jen/python/optional labs
  code/Jen/Python/10_rotcipherv2.py
  code/Jen/Python/count_words.py
  code/Jen/Python/hackers.txt
Labels: optional lab

#117 Tony/python/lab04
  code/tony/python/lab04version3.py
  code/tony/python/lab04version4.py
Labels: optional lab
