Repository PdxCodeGuild/class_orchid, pull requests merged in 2022-08, with the labels that each got.

#159 Lab 11 complete, Thank you
  code/teyon/python/data/theclouds.txt
  code/teyon/python/labs/lab11.py
Labels: complete

#171 lab 08 solution
  1 Python/labs/solutions/lab08.py
Labels: complete

#161 Lab10 ROT13 with Version 2 Complete
  code/jordyn/python/lab10.py
Labels: complete

#165 Lab 11 completed version
  code/mileidy/python/lab11_version1.py
  code/mileidy/python/yellow/the-yellow-wallpaper.txt
Labels: complete

#170 lab 12 and csv file added.
  code/Jen/Python/12contact_listv3.py
  code/Jen/Python/rabbits.csv
Labels: complete

#166 Lab11 completed
  code/jordyn/python/Around_The_World_In_80_Days.txt
  code/jordyn/python/lab11.py
Labels: complete

#173 Patrick/python/lab12
  code/patrick/python/data/contacts.csv
  code/patrick/python/data/contacts2.csv
  code/patrick/python/lab12.py
Labels: complete

#179 lab12 v1, v2, v3 complete
  code/teyon/python/data/contacts.csv
  code/teyon/python/labs/lab12.py
  code/teyon/python/labs/lab12v2.py
  code/teyon/python/labs/lab12v3.py
Labels: complete

#164 Tony/python/lab12
  code/tony/python/data/lab12_data.csv
  code/tony/python/lab12_version1.py
  code/tony/python/lab12_version2.py
  code/tony/python/lab12_version3.py
Labels: complete

#176 Vel/python/lab12
  code/vel/python/chiefs/chiefs_goat2.csv
  code/vel/python/chiefs/chiefs_goats.csv
  code/vel/python/chiefs_goat2.csv
  code/vel/python/lab12.py
Labels: complete

#177 rob/python/lab15
  code/rob/python/lab15.py
Labels: optional lab

#162 Rob/python/lab12
  code/rob/python/lab12/lab12.csv
  code/rob/python/lab12/lab12.py
Labels: complete

#168 Tony/python/lab13
  code/tony/python/classes/lab13version1.py
  code/tony/python/classes/lab13version2.py
  code/tony/python/lab13_version1.py
  code/tony/python/lab13_version2.py
Labels: complete

#163 rob/python/lab13
  code/rob/python/lab13/lab13.py
  code/rob/python/lab13/lab13_atm.py
Labels: complete

#174 Lab 13
  code/Jen/Python/13_atmv2.py
Labels: complete

#178 lab13.py is done and ready for grading.
  code/cesar/python/lab13.py
Labels: complete

#184 Lab13 complete
  code/vel/python/lab13.py
Labels: complete

#210 Faith/python/lab13
  code/faith/python/lab13/lab13.py
Labels: complete

#199 Teyon/python/lab18
  code/teyon/python/data/airports.csv
  code/teyon/python/labs/lab18.py
Labels: complete

#197 completed lab17
  code/mileidy/python/lab16_version1.py
  code/mileidy/python/lab16_version2.py
Labels: complete

#194 Lab12 is complete. contact.csv is the original file and the write file is contacs2.csv
  code/cesar/python/contact.csv
  code/cesar/python/contact2.csv
  code/cesar/python/lab12.py
Labels: complete

#180 Faith/python/lab12
  code/faith/python/backupcontacts.csv
  code/faith/python/contact.csv
  code/faith/python/lab12.py
Labels: complete

#186 part 1 & 2
  code/rob/python/lab17/.gitignore
  code/rob/python/lab17/lab17_v1.py
  code/rob/python/lab17/lab17_v2.py
Labels: complete

#187 lab16
  code/faith/python/lab16.py
Labels: complete

#183 lab 17
  code/tony/python/lab17version1.py
  code/tony/python/lab17version2.py
Labels: complete

#169 lab13 ready for grading
  code/patrick/python/lab13.py
Labels: complete

#185 Patrick/python/lab16
  code/mobs/teamsunshine/lab14.py
  code/patrick/python/lab16.py
Labels: complete

#190 Lab 17 added
  code/Jen/Python/17_quotesapiv2.py
Labels: complete

#196 Jordyn/python/lab17
  code/jordyn/python/lab17.py
Labels: complete

#172 Jordyn/python/lab12
  code/jordyn/python/lab12.py
  code/jordyn/python/lab12_contacts_main.csv
Labels: complete

#175 Lab13 complete
  code/jordyn/python/lab13.py
Labels: complete

#181 lab 16
  code/tony/python/lab16part1.py
  code/tony/python/lab16part2.py
Labels: complete

#182 rob/python/lab16
  code/rob/python/lab16.py
Labels: complete

#188 Lab 16v2
  code/Jen/Python/16_dadjokev2.py
Labels: complete

#191 lab17ver1 and ver2 ready for grading
  code/patrick/python/lab17ver1.py
  code/patrick/python/lab17ver2.py
Labels: complete

#195 Jordyn/python/lab16
  code/jordyn/python/lab16.py
Labels: complete

#192 lab13 complete. Thank you
  code/teyon/python/labs/lab13.py
  code/teyon/python/labs/lab13v2.py
Labels: complete

#214 Lab 16 versions 1 and 2
  code/vel/python/lab16ver1.py
  code/vel/python/lab16ver2.py
Labels: complete

#189 lab 16 complete
  code/teyon/python/labs/lab16.py
Labels: complete

#217 lab17 versions 1 & 2
  code/vel/python/lab17ver1.py
  code/vel/python/lab17ver2.py
Labels: complete

#203 Teyon/python/lab17
  code/teyon/python/labs/lab17.py
  code/teyon/python/labs/lab17v2.py
Labels: complete

#202 Lab16 Python is now done. Thanks!
  code/cesar/python/lab16.py
  code/cesar/python/lab16v2.py
Labels: complete

#221 Mileidy/python/lab17
  code/mileidy/python/lab17_version1.py
  code/mileidy/python/lab17_version2.py
  code/mileidy/python/test.py
Labels: complete

#232 lab01 css and html
  code/mileidy/HTML_CSS/lab01/berries.jpg
  code/mileidy/HTML_CSS/lab01/luffy.jpg
  code/mileidy/HTML_CSS/lab01/one-piece-wallpaper-40.jpg
  code/mileidy/HTML_CSS/lab01/version1.css
  code/mileidy/HTML_CSS/lab01/version1.html
Labels: complete

#220 HTML/CSS lab 01 complete
  code/teyon/html+css/Lab01/index.html
  code/teyon/html+css/Lab01/style.css
Labels: complete

#215 rob/html/lab1
  code/rob/html/lab1/bio.css
  code/rob/html/lab1/bio.html
Labels: complete

#227 lab01 html
  code/vel/html/lab01/andy reid.jpeg
  code/vel/html/lab01/dave-adamson-rPUDwwLSohI-unsplash.jpg
  code/vel/html/lab01/lab01.css
  code/vel/html/lab01/lab01.html
Labels: complete

#216 cesar/htmlcss/lab01
  code/cesar/html_css/lab01_bio/TempleOS_logo.png
  code/cesar/html_css/lab01_bio/elephant.png
  code/cesar/html_css/lab01_bio/main.html
  code/cesar/html_css/lab01_bio/styles.css
  code/cesar/html_css/lab01_bio/terrydavis.jpg
Labels: complete

#212 html Lab 1
  code/Jen/Python/lab4v1.py
  code/Jen/Python/lab4v2.py
  code/Jen/Python/lab5v1.py
  code/Jen/html/angela.html
Labels: complete

#204 lab01 complete
  code/tony/htmlcss/lab01/background.jpg
  code/tony/htmlcss/lab01/dalecooper.jpg
  code/tony/htmlcss/lab01/index.html
  code/tony/htmlcss/lab01/styles.css
Labels: complete

#209 Patrick/html/lab01
  code/patrick/html/lab01/lab01.css
  code/patrick/html/lab01/lab01.html
Labels: complete

#206 Faith/html/lab01
  code/faith/HTML/lab01html/blood-drop.png
  code/faith/HTML/lab01html/ichigo.jpeg
  code/faith/HTML/lab01html/ichigobackground.jpeg
  code/faith/HTML/lab01html/ichigokid.jpeg
  code/faith/HTML/lab01html/lab01.css
  code/faith/HTML/lab01html/lab01.html
  code/faith/python/OrderUp/OrderUp_app/__init__.py
  code/faith/python/OrderUp/OrderUp_app/admin.py
  code/faith/python/OrderUp/OrderUp_app/apps.py
  code/faith/python/OrderUp/OrderUp_app/migrations/0001_initial.py
  code/faith/python/OrderUp/OrderUp_app/migrations/__init__.py
  code/faith/python/OrderUp/OrderUp_app/models.py
  code/faith/python/OrderUp/OrderUp_app/static/002-vegan-1.png
  code/faith/python/OrderUp/OrderUp_app/static/base.css
  code/faith/python/OrderUp/OrderUp_app/static/burger.png
  code/faith/python/OrderUp/OrderUp_app/static/cooking.png
  code/faith/python/OrderUp/OrderUp_app/static/leaf.png
  code/faith/python/OrderUp/OrderUp_app/static/thankyou.css
  code/faith/python/OrderUp/OrderUp_app/static/welcome.css
  code/faith/python/OrderUp/OrderUp_app/templates/base.html
  code/faith/python/OrderUp/OrderUp_app/templates/thankyou.html
  code/faith/python/OrderUp/OrderUp_app/templates/welcome.html
  code/faith/python/OrderUp/OrderUp_app/tests.py
  code/faith/python/OrderUp/OrderUp_app/urls.py
  code/faith/python/OrderUp/OrderUp_app/views.py
  code/faith/python/OrderUp/OrderUp_project/__init__.py
  code/faith/python/OrderUp/OrderUp_project/asgi.py
  code/faith/python/OrderUp/OrderUp_project/settings.py
  code/faith/python/OrderUp/OrderUp_project/urls.py
  code/faith/python/OrderUp/OrderUp_project/wsgi.py
  code/faith/python/OrderUp/Pipfile
  code/faith/python/OrderUp/Pipfile.lock
  code/faith/python/OrderUp/manage.py
Labels: complete

#224 challenge ACCEPTED!
  code/tony/htmlcss/lab02/glue.jpg
  code/tony/htmlcss/lab02/index.html
  code/tony/htmlcss/lab02/main.css
  code/tony/htmlcss/lab02/shocked-beard.jpg
  code/tony/htmlcss/lab02/shocked-woman.jpg
  code/tony/htmlcss/lab02/surprised-woman.jpg
Labels: complete

#225 Faith/python/lab17
  code/faith/python/lab17.py
Labels: incomplete

#235 lab02 complete
  code/teyon/html+css/lab02/index.html
  code/teyon/html+css/lab02/style.css
  code/teyon/python/labs/lab02.py
  code/teyon/python/labs/lab02v2.py
  code/teyon/python/labs/lab03.py
  code/teyon/python/labs/lab04v1.py
  code/teyon/python/labs/lab04v2.py
  code/teyon/python/labs/lab05.py
  code/teyon/python/labs/lab06.py
  code/teyon/python/labs/lab06v2.py
  code/teyon/python/labs/lab08.py
  code/teyon/python/labs/lab09.py
Labels: complete

#236 rob/html/lab3
  code/rob/html/lab3/facebook.png
  code/rob/html/lab3/instagram.png
  code/rob/html/lab3/lab3.css
  code/rob/html/lab3/lab3.html
Labels: complete

#223 html lab 2
  code/Jen/html/02_Depositphotos_57307583_XL.jpg
  code/Jen/html/02_companyhome.html
  code/Jen/html/02_logowtext.jpg
  code/Jen/html/02_november.jpg
  code/Jen/html/02_stylesheet.css
Labels: complete

#231 rob/html/lab2
  code/rob/html/lab2/lab2.css
  code/rob/html/lab2/lab2.html
Labels: complete

#222 Mileidy/python/lab18
  code/mileidy/mini_capstone_python/api.py
  code/mileidy/mini_capstone_python/trivia.py
Labels: complete
